// <auto-generated />
using System;
using InscrieriStudenti.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InscrieriStudenti.Migrations
{
    [DbContext(typeof(StudentiContext))]
    [Migration("20211217111259_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("InscrieriStudenti.Entities.Ani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdCurs")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ani");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.CamereCamin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Etaj")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int>("Suprafata")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdStudent")
                        .IsUnique();

                    b.ToTable("CamereCamin");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Catalog", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int>("IdCurs")
                        .HasColumnType("int");

                    b.Property<int>("An")
                        .HasColumnType("int");

                    b.HasKey("IdStudent", "IdCurs");

                    b.HasIndex("IdCurs");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Cursuri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AniId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZiCursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AniId");

                    b.HasIndex("ZiCursId");

                    b.ToTable("Cursuri");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Studenti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AniId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AniId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.ZiCurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdCurs")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZiCurs");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.CamereCamin", b =>
                {
                    b.HasOne("InscrieriStudenti.Entities.Studenti", "Studenti")
                        .WithOne("CamereCamin")
                        .HasForeignKey("InscrieriStudenti.Entities.CamereCamin", "IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Catalog", b =>
                {
                    b.HasOne("InscrieriStudenti.Entities.Cursuri", "Cursuri")
                        .WithMany("CursStudent")
                        .HasForeignKey("IdCurs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InscrieriStudenti.Entities.Studenti", "Studenti")
                        .WithMany("CursStudent")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cursuri");

                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Cursuri", b =>
                {
                    b.HasOne("InscrieriStudenti.Entities.Ani", null)
                        .WithMany("Cursuri")
                        .HasForeignKey("AniId");

                    b.HasOne("InscrieriStudenti.Entities.ZiCurs", "ZiCurs")
                        .WithMany("Cursuri")
                        .HasForeignKey("ZiCursId");

                    b.Navigation("ZiCurs");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Studenti", b =>
                {
                    b.HasOne("InscrieriStudenti.Entities.Ani", null)
                        .WithMany("Studenti")
                        .HasForeignKey("AniId");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Ani", b =>
                {
                    b.Navigation("Cursuri");

                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Cursuri", b =>
                {
                    b.Navigation("CursStudent");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.Studenti", b =>
                {
                    b.Navigation("CamereCamin");

                    b.Navigation("CursStudent");
                });

            modelBuilder.Entity("InscrieriStudenti.Entities.ZiCurs", b =>
                {
                    b.Navigation("Cursuri");
                });
#pragma warning restore 612, 618
        }
    }
}
